title: Aiden McVean's Portfolio
description: This contains Aiden McVean's projects, information, and experience as a Data Scientist.
baseurl: ""
url: https://amcvean.github.io

remote_theme: cvless

# site settings
taglong: Jekyll theme for a beautiful online CV
tagshort: Jekyll theme

# author settings
author:
  name: Aiden McVean
  email: amcvean@mtu.edu
photo: assets/files/photo.jpg
address: Houghton, MI
phone: (248)-894-6955

# social media links
social:
  facebook: 
  x: 
  instagram: 
  linkedin: 
  xing: 
  stackoverflow: 
  medium: 
  github: amcvean

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
